// ===================================== ПЕРЕВОД ИНТЕРФЕЙСА: русский → English ====================
// Ключ — точная русская строка из исходников (после разбора escape), значение — английский перевод.
// Спецификаторы printf (%d, %.2f, %s …) в переводе — те же и в том же порядке: строка может быть форматом fmt().
// Файл поддерживается скриптом tools/i18n.py (check / todo / merge / rewrite); порядок — как в исходниках.
// Новые строки интерфейса: python tools/i18n.py todo --json todo.json → перевести → python tools/i18n.py merge todo.json
static const char* const LANG_TABLE[][2] = {
    // ---- src/analysis.inl
    {"газ", "gas"},
    {"жидкость", "liquid"},
    {"твёрдое", "solid"},
    {"стенка", "wall"},
    {"аморфн.", "amorph."},
    {"ГЦК", "FCC"},
    {"ГПУ", "HCP"},
    {"ОЦК", "BCC"},
    {"ПК/NaCl", "SC/NaCl"},
    {"гекс.", "hex."},
    {"квадр.", "sq."},
    {"лёд", "ice"},
    {"твёрдое + жидкость", "solid + liquid"},
    {"сверхкритический флюид", "supercritical fluid"},
    {"газ + жидкость", "gas + liquid"},
    {"твёрдое + газ", "solid + gas"},
    {"t=%.1fτ (%.0f пс)  ", "t=%.1fτ (%.0f ps)  "},
    {" при T* %.3f→%.3f (%.0f→%.0f K)", " at T* %.3f→%.3f (%.0f→%.0f K)"},
    {"сублимация (твёрдое → газ)", "sublimation (solid → gas)"},
    {"плавление", "melting"},
    {"десублимация (газ → твёрдое)", "deposition (gas → solid)"},
    {"кристаллизация", "crystallization"},
    {": твёрдое %.0f%% → %.0f%%", ": solid %.0f%% → %.0f%%"},
    {",  ΔH ≈ %+.2f ε/ат (%+.2f кДж/моль)", ",  ΔH ≈ %+.2f ε/at (%+.2f kJ/mol)"},
    {" (плато T не выражено — ΔH не оценивается)", " (no clear T plateau — ΔH not estimated)"},
    {"возгонка (твёрдое → газ)", "sublimation (solid → gas)"},
    {"кипение / испарение", "boiling / evaporation"},
    {"конденсация", "condensation"},
    {": газ %.0f%% → %.0f%%", ": gas %.0f%% → %.0f%%"},
    {"кристалл", "crystal"},
    {"поликристалл (зёрна, границы, дефекты)", "polycrystal (grains, boundaries, defects)"},
    {"стекло (аморфное твёрдое)", "glass (amorphous solid)"},
    {"три фазы: твёрдое + жидкость + пар", "three phases: solid + liquid + vapor"},
    {"плавление: кристалл + жидкость", "melting: crystal + liquid"},
    {"кристаллизация: жидкость + кристалл", "crystallization: liquid + crystal"},
    {"твёрдое + жидкость (сосуществование)", "solid + liquid (coexistence)"},
    {"испарение: жидкость + пар", "evaporation: liquid + vapor"},
    {"конденсация: пар + капли жидкости", "condensation: vapor + liquid droplets"},
    {"жидкость + пар (сосуществование)", "liquid + vapor (coexistence)"},
    {"сублимация: твёрдое + пар", "sublimation: solid + vapor"},
    {"десублимация: пар → твёрдое (иней)", "deposition: vapor → solid (frost)"},
    {"твёрдое + пар", "solid + vapor"},
    // ---- src/app.inl
    {"Полный экран (F11 или Esc — выйти)", "Full screen (F11 or Esc — exit)"},
    {"Оконный режим", "Windowed mode"},
    {"Файл ИНСТРУКЦИЯ.html не найден рядом с atoms.exe", "MANUAL.html not found next to atoms.exe"},
    {"Инструкция открыта в браузере", "Manual opened in the browser"},
    {"Не удалось записать файл", "Could not write the file"},
    {"Состояние сохранено", "State saved"},
    {"Ошибка записи файла", "File write error"},
    {"Быстрое сохранение (F9 — загрузить)", "Quick save (F9 — load)"},
    {"Файл не найден", "File not found"},
    {"Это не файл состояния «Атомы» (или другая версия)", "Not an Atoms state file (or a different version)"},
    {"Файл повреждён", "File is corrupted"},
    {"Файл повреждён — состояние не изменено", "File is corrupted — state unchanged"},
    {"  [загружено]", "  [loaded]"},
    {"Состояние загружено", "State loaded"},
    {"Состояние загружено (файл версии 2)", "State loaded (version 2 file)"},
    {"Отмена", "Undone"},
    {"Не удалось создать CSV", "Could not create the CSV file"},
    {"Атомы — экспорт;%s;%dD;N=%d;t=%s\n\n", "Atoms — export;%s;%dD;N=%d;t=%s\n\n"},
    {"Временные ряды\nt;T;P;Eкин;Eпот;Eполн\n", "Time series\nt;T;P;Ekin;Epot;Etot\n"},
    {"\nРаспределение скоростей\nv;f(v) измер.;f(v) Максвелл\n", "\nSpeed distribution\nv;f(v) measured;f(v) Maxwell\n"},
    {"\nMSD\nt;MSD;MSD броун. частицы\n", "\nMSD\nt;MSD;MSD Brownian particle\n"},
    {"\nЧисло молекул (отсчёты)\nотсчёт", "\nNumber of molecules (samples)\nsample"},
    {"Экспорт: ", "Exported: "},
    {"Время обращено: v → −v (хаос быстро разрушит обратимость)", "Time reversed: v → −v (chaos will soon destroy reversibility)"},
    {"Снимок: ", "Snapshot: "},
    {" (рядом с atoms.exe)", " (next to atoms.exe)"},
    {"Не удалось записать снимок", "Could not save the snapshot"},
    {"Запись остановлена: %d кадров → ", "Recording stopped: %d frames → "},
    {"Не удалось создать папку для кадров", "Could not create the frames folder"},
    {"Запись кадров сцены (каждый 2-й кадр, PNG). Ctrl+F12 — остановить", "Recording scene frames (every 2nd frame, PNG). Ctrl+F12 — stop"},
    {"Выделено атомов: %d", "Atoms selected: %d"},
    {"Цвет: ", "Color: "},
    {"Нечего закреплять: выделите атомы (Alt+2)", "Nothing to pin: select atoms first (Alt+2)"},
    {"Объект включён", "Object on"},
    {"Объект выключен", "Object off"},
    {"Полёт: WASD — движение, Q/E — вниз/вверх, Shift — быстрее, Ctrl+ЛКМ — осмотреться", "Fly mode: WASD — move, Q/E — down/up, Shift — faster, Ctrl+LMB — look around"},
    {"Камера: орбита вокруг центра", "Camera: orbit around the center"},
    {"Режим полёта — только в 3D (клавиша D)", "Fly mode — 3D only (key D)"},
    {"Разрез: видно только то, что за плоскостью. Shift+колесо — сдвиг", "Cross-section: only what lies behind the plane is shown. Shift+wheel — move it"},
    {"Разрез выключен", "Cross-section off"},
    {"Разрез — только в 3D (клавиша D)", "Cross-section — 3D only (key D)"},
    {"Катализатор: Ea×0.25 внутри", "Catalyst: Ea×0.25 inside"},
    {"Катализатор убран", "Catalyst removed"},
    {"Сжатие по x −2%", "Compressed along x: −2%"},
    {"Растяжение по x +2%", "Stretched along x: +2%"},
    {"Вид спереди", "Front view"},
    {"Вид сбоку", "Side view"},
    {"Вид сверху", "Top view"},
    {"Изометрия", "Isometric view"},
    {"Слежение за атомом выключено", "Atom following off"},
    {"Камера следит за атомом #%d (%s). Esc — стоп", "Camera follows atom #%d (%s). Esc — stop"},
    {"Слежение выключено", "Following off"},
    {"Вставлено: ", "Inserted: "},
    {"Не помещается — выберите свободное место", "Does not fit — pick a free spot"},
    {"Разорвано связей: %d", "Bonds broken: %d"},
    {"Выделено атомов: %d · Del — удалить, Ctrl+C — копировать, I — закрепить, Alt+тащить — бросок", "Atoms selected: %d · Del — delete, Ctrl+C — copy, I — pin, Alt+drag — throw"},
    {"Бросок: скорость центра масс %.2f σ/τ = %.0f м/с (энергия — в W)", "Throw: center-of-mass velocity %.2f σ/τ = %.0f m/s (energy goes to W)"},
    {"\n[%d] %s\n  N=%d  steps=%d  %.2f s (%.0f steps/s, %d пересборок списка)  t=%.2f dt=%.4f\n", "\n[%d] %s\n  N=%d  steps=%d  %.2f s (%.0f steps/s, %d list rebuilds)  t=%.2f dt=%.4f\n"},
    {"\nLATTICES (%dD): 400 шагов при T=0.1\n", "\nLATTICES (%dD): 400 steps at T=0.1\n"},
    {"NaN у атома %d", "NaN at atom %d"},
    {"плохой атом %d", "bad atom %d"},
    {"несимметричная связь %d-%d", "asymmetric bond %d-%d"},
    {"несимметричный призрак %d-%d", "asymmetric ghost %d-%d"},
    {"энергия не конечна", "energy is not finite"},
    {"работа W не конечна", "work W is not finite"},
    {"висячий индекс пинцета/слежения", "dangling tweezers/follow index"},
    {"размер pin %d ≠ N %d", "pin size %d ≠ N %d"},
    {"индекс выделения вне диапазона", "selection index out of range"},
    {"объект поля с некорректными параметрами", "field object with invalid parameters"},
    {"висячий индекс объекта поля", "dangling field object index"},
    {"клавиша %d", "key %d"},
    {"клавиша %d+%d", "key %d+%d"},
    {"щелчок по элементу %d", "click on element %d"},
    {"слайдер %d", "slider %d"},
    {"щелчок по атому %d", "click on atom %d"},
    {"пауза %d кадров", "wait %d frames"},
    {"все элементы %d–%d", "all elements %d–%d"},
    {"панель: элемент %d", "panel: element %d"},
    {"     панель %d: элементов %zu\n", "     panel %d: %zu elements\n"},
    {"кисть", "brush"},
    {"атомы элемента", "element atoms"},
    {"щелчок мимо таблицы", "click outside the table"},
    {"инструмент", "tool"},
    {"поставить объект", "place object"},
    {"колесо над объектом", "wheel over object"},
    {"Shift+колесо над объектом", "Shift+wheel over object"},
    {"перенос объекта", "move object"},
    {"ПКМ по объекту — удалить", "RMB on object — delete"},
    {"выбрать объект", "select object"},
    {"рамка", "selection box"},
    {"перенос выделения", "move selection"},
    {"бросок (Alt)", "throw (Alt)"},
    {"Alt+колесо — поворот", "Alt+wheel — rotate"},
    {"рамка + Shift", "selection box + Shift"},
    {"курсор в угол", "cursor to corner"},
    {"рамка 2", "selection box 2"},
    {"сброс измерения", "reset measurement"},
    {"толчок", "push"},
    {"притяжение", "pull"},
    {"удар", "shock"},
    {"ножницы", "scissors"},
    {"ножницы 2", "scissors 2"},
    {"пинцет", "tweezers"},
    {"двойной щелчок — слежение", "double-click — follow"},
    {"нагрев", "heat"},
    {"охлаждение", "cool"},
    {"ластик", "eraser"},
    {"вращение/сдвиг", "rotate/pan"},
    {"сдвиг 3D", "pan 3D"},
    {"колесо", "wheel"},
    {"колесо над слайдером", "wheel over slider"},
    {"прокрутка вкладки", "tab scrolling"},
    {"полёт WASDQE", "fly WASDQE"},
    {"осмотр в полёте", "look around in flight"},
    {"сдвиг разреза", "move cross-section"},
    {"кисть при разрезе", "brush with cross-section"},
    {"объекты для сохранения", "objects for saving"},
    {"очистить объекты", "clear objects"},
    {"проверка загрузки v3", "v3 load check"},
    {"     ОШИБКА: после F9 объектов %d (ожидалось %d), pin[0]=%d\n", "     ERROR: after F9 %d objects (expected %d), pin[0]=%d\n"},
    {"     загрузка v3: объекты поля и закрепление восстановлены\n", "     v3 load: field objects and pins restored\n"},
    {"рисуем стену", "draw a wall"},
    {"стереть всё", "erase everything"},
    {"большой ластик", "big eraser"},
    {"стереть всё 2", "erase everything 2"},
    {"кисть обратно", "brush back"},
    {"ОШИБКА: ", "ERROR: "},
    {"     ОШИБКА: перегрев после шага «%s»: T %.2f → %.2f\n", "     ERROR: overheating after step “%s”: T %.2f → %.2f\n"},
    {"# t=%.2f T=%.3f dt=%.5f  E−W=%.4f (Δ за 500 шагов %.4f)  сумма ΔE событий %.3e  capped=%d\n", "# t=%.2f T=%.3f dt=%.5f  E−W=%.4f (Δ over 500 steps %.4f)  sum of event ΔE %.3e  capped=%d\n"},
    {"шагов сценария: %zu\n", "script steps: %zu\n"},
    {"H — справка · D — 2D/3D · Alt+1…0 — инструменты · 1–9, 0 — сцены", "H — help · D — 2D/3D · Alt+1…0 — tools · 1–9, 0 — scenes"},
    {"\nИТОГ: шагов %zu из %zu, проблем %d\n", "\nTOTAL: steps %zu of %zu, problems %d\n"},
    // ---- src/chemistry.inl
    {"(сетка)", "(network)"},
    {"Стена", "Wall"},
    {"ПК", "SC"},
    {"кристалл NaCl", "NaCl crystal"},
    {"алмаз", "diamond"},
    {"графен", "graphene"},
    {"вода: угол H–O–H 104.5°, O–H 0.96 Å, заряды как SPC/E", "water: H–O–H angle 104.5°, O–H 0.96 Å, SPC/E-like charges"},
    {"пероксид водорода: O–O 1.48 Å, двугранный угол 111°", "hydrogen peroxide: O–O 1.48 Å, dihedral angle 111°"},
    {"углекислый газ: линейная, C=O 1.20 Å", "carbon dioxide: linear, C=O 1.20 Å"},
    {"угарный газ (в модели C=O; в природе тройная связь C≡O)", "carbon monoxide (C=O in the model; in nature a triple bond C≡O)"},
    {"метан: тетраэдр, C–H 1.09 Å, 4.3 эВ на связь", "methane: tetrahedron, C–H 1.09 Å, 4.3 eV per bond"},
    {"этан: C–C 1.54 Å, 3.6 эВ", "ethane: C–C 1.54 Å, 3.6 eV"},
    {"этилен: плоская, C=C 1.34 Å, 6.4 эВ", "ethylene: planar, C=C 1.34 Å, 6.4 eV"},
    {"ацетилен: линейная, C≡C 1.20 Å, 8.7 эВ", "acetylene: linear, C≡C 1.20 Å, 8.7 eV"},
    {"метанол CH3OH", "methanol CH3OH"},
    {"этанол C2H5OH (горит: C2H5OH + 3O2 → 2CO2 + 3H2O)", "ethanol C2H5OH (burns: C2H5OH + 3O2 → 2CO2 + 3H2O)"},
    {"бензол: кольцо Кекуле (чередование C–C и C=C)", "benzene: Kekulé ring (alternating C–C and C=C)"},
    {"аммиак: пирамида, угол 107°", "ammonia: pyramid, angle 107°"},
    {"хлороводород: H–Cl 1.27 Å, 4.43 эВ; в воде — сильная кислота", "hydrogen chloride: H–Cl 1.27 Å, 4.43 eV; a strong acid in water"},
    {"азот: N≡N 1.10 Å, 9.79 эВ — самая прочная связь", "nitrogen: N≡N 1.10 Å, 9.79 eV — the strongest bond"},
    {"кислород: O=O 1.21 Å, 5.12 эВ", "oxygen: O=O 1.21 Å, 5.12 eV"},
    {"водород: H–H 0.74 Å, 4.52 эВ", "hydrogen: H–H 0.74 Å, 4.52 eV"},
    {"хлор: Cl–Cl 1.99 Å, 2.48 эВ", "chlorine: Cl–Cl 1.99 Å, 2.48 eV"},
    {"озон O=O⁺–O⁻ (биполярный ион): неустойчив, распадается при нагреве", "ozone O=O⁺–O⁻ (dipolar ion): unstable, decomposes when heated"},
    {"ион гидроксония H3O+ (кислота): протон переходит к соседней воде", "hydronium ion H3O+ (acid): the proton hops to a neighboring water"},
    {"гидроксид-ион OH− (основание): нейтрализует H3O+", "hydroxide ion OH− (base): neutralizes H3O+"},
    {"ион аммония NH4+", "ammonium ion NH4+"},
    {"гидроксид натрия: Na+ и OH− (щёлочь)", "sodium hydroxide: Na+ and OH− (alkali)"},
    {"ионная пара Na+ Cl−", "ion pair Na+ Cl−"},
    {"кристаллик NaCl (решётка каменной соли)", "small NaCl crystal (rock-salt lattice)"},
    {"кластер алмаза, поверхность закрыта водородом (C–C 1.54 Å, sp3)", "diamond cluster, surface capped with hydrogen (C–C 1.54 Å, sp3)"},
    {"лист графена: соты sp2, структура Кекуле, край закрыт водородом", "graphene sheet: sp2 honeycomb, Kekulé structure, edge capped with hydrogen"},
    {"кубический лёд Ic: 64 молекулы, правила Бернала–Фаулера (только 3D)", "cubic ice Ic: 64 molecules, Bernal–Fowler rules (3D only)"},
    {"кремнезём: сетка SiO4 (кристобалит), поверхность — группы Si–OH", "silica: SiO4 network (cristobalite), Si–OH groups on the surface"},
    {"кластер платины (ГЦК): катализатор окисления водорода", "platinum cluster (FCC): catalyst for hydrogen oxidation"},
    {"кластер золота (ГЦК)", "gold cluster (FCC)"},
    {"кластер железа: катализатор, ржавеет в O2", "iron cluster: catalyst, rusts in O2"},
    {"кластер никеля: катализатор гидрирования", "nickel cluster: hydrogenation catalyst"},
    // ---- src/core.inl
    {"щелочной металл", "alkali metal"},
    {"щёлочноземельный металл", "alkaline earth metal"},
    {"переходный металл", "transition metal"},
    {"постпереходный металл", "post-transition metal"},
    {"полуметалл", "metalloid"},
    {"неметалл", "non-metal"},
    {"галоген", "halogen"},
    {"благородный газ", "noble gas"},
    {"лантаноид", "lanthanide"},
    {"актиноид", "actinide"},
    {"особый тип", "special type"},
    {"аргон", "argon"},
    {"неон", "neon"},
    {"водород", "hydrogen"},
    {"углерод", "carbon"},
    {"азот", "nitrogen"},
    {"кислород", "oxygen"},
    {"ион натрия", "sodium ion"},
    {"хлор", "chlorine"},
    {"хлорид-ион", "chloride ion"},
    {"броун. частица", "Brownian particle"},
    {"гелий", "helium"},
    {"литий", "lithium"},
    {"бериллий", "beryllium"},
    {"бор", "boron"},
    {"фтор", "fluorine"},
    {"натрий", "sodium"},
    {"магний", "magnesium"},
    {"алюминий", "aluminium"},
    {"кремний", "silicon"},
    {"фосфор", "phosphorus"},
    {"сера", "sulfur"},
    {"калий", "potassium"},
    {"кальций", "calcium"},
    {"скандий", "scandium"},
    {"титан", "titanium"},
    {"ванадий", "vanadium"},
    {"хром", "chromium"},
    {"марганец", "manganese"},
    {"железо", "iron"},
    {"кобальт", "cobalt"},
    {"никель", "nickel"},
    {"медь", "copper"},
    {"цинк", "zinc"},
    {"галлий", "gallium"},
    {"германий", "germanium"},
    {"мышьяк", "arsenic"},
    {"селен", "selenium"},
    {"бром", "bromine"},
    {"криптон", "krypton"},
    {"рубидий", "rubidium"},
    {"стронций", "strontium"},
    {"иттрий", "yttrium"},
    {"цирконий", "zirconium"},
    {"ниобий", "niobium"},
    {"молибден", "molybdenum"},
    {"технеций", "technetium"},
    {"рутений", "ruthenium"},
    {"родий", "rhodium"},
    {"палладий", "palladium"},
    {"серебро", "silver"},
    {"кадмий", "cadmium"},
    {"индий", "indium"},
    {"олово", "tin"},
    {"сурьма", "antimony"},
    {"теллур", "tellurium"},
    {"иод", "iodine"},
    {"ксенон", "xenon"},
    {"цезий", "caesium"},
    {"барий", "barium"},
    {"лантан", "lanthanum"},
    {"церий", "cerium"},
    {"празеодим", "praseodymium"},
    {"неодим", "neodymium"},
    {"прометий", "promethium"},
    {"самарий", "samarium"},
    {"европий", "europium"},
    {"гадолиний", "gadolinium"},
    {"тербий", "terbium"},
    {"диспрозий", "dysprosium"},
    {"гольмий", "holmium"},
    {"эрбий", "erbium"},
    {"тулий", "thulium"},
    {"иттербий", "ytterbium"},
    {"лютеций", "lutetium"},
    {"гафний", "hafnium"},
    {"тантал", "tantalum"},
    {"вольфрам", "tungsten"},
    {"рений", "rhenium"},
    {"осмий", "osmium"},
    {"иридий", "iridium"},
    {"платина", "platinum"},
    {"золото", "gold"},
    {"ртуть", "mercury"},
    {"таллий", "thallium"},
    {"свинец", "lead"},
    {"висмут", "bismuth"},
    {"полоний", "polonium"},
    {"астат", "astatine"},
    {"радон", "radon"},
    {"франций", "francium"},
    {"радий", "radium"},
    {"актиний", "actinium"},
    {"торий", "thorium"},
    {"протактиний", "protactinium"},
    {"уран", "uranium"},
    {"нептуний", "neptunium"},
    {"плутоний", "plutonium"},
    {"америций", "americium"},
    {"кюрий", "curium"},
    {"берклий", "berkelium"},
    {"калифорний", "californium"},
    {"эйнштейний", "einsteinium"},
    {"фермий", "fermium"},
    {"менделевий", "mendelevium"},
    {"нобелий", "nobelium"},
    {"лоуренсий", "lawrencium"},
    {"резерфордий", "rutherfordium"},
    {"дубний", "dubnium"},
    {"сиборгий", "seaborgium"},
    {"борий", "bohrium"},
    {"хассий", "hassium"},
    {"мейтнерий", "meitnerium"},
    {"дармштадтий", "darmstadtium"},
    {"рентгений", "roentgenium"},
    {"коперниций", "copernicium"},
    {"нихоний", "nihonium"},
    {"флеровий", "flerovium"},
    {"московий", "moscovium"},
    {"ливерморий", "livermorium"},
    {"теннессин", "tennessine"},
    {"оганесон", "oganesson"},
    {"Берендсен", "Berendsen"},
    {"Нозе–Гувер", "Nosé–Hoover"},
    {"нагрев P", "power heating"},
    {"Бусси", "Bussi"},
    {"Ланжевен", "Langevin"},
    {"периодич.", "periodic"},
    {"стенки", "walls"},
    {"поршень", "piston"},
    // ---- src/panel_chem.inl
    {"%s — только в 3D (клавиша D)", "%s — 3D only (key D)"},
    {"%s: %s. ЛКМ в сцене — вставить", "%s: %s. LMB in the scene — insert"},
    {"Реакции", "Reactions"},
    {"химические реакции (связи рвутся и образуются)", "chemical reactions (bonds break and form)"},
    {"Ассоциация радикалов, обмен атомами, диссоциация перерастянутых связей.\nЭнергия каждого события сохраняется точно", "Radical association, atom exchange, dissociation of overstretched bonds.\nThe energy of every event is conserved exactly"},
    {"кислоты и основания (перенос протона)", "acids and bases (proton transfer)"},
    {"H3O+ + H2O ⇌ H2O + H3O+ (механизм Гроттгуса), HCl + H2O → H3O+ + Cl−,\nH3O+ + OH− → 2H2O, NH3 + H3O+ → NH4+ + H2O. Самоионизация воды не моделируется", "H3O+ + H2O ⇌ H2O + H3O+ (Grotthuss mechanism), HCl + H2O → H3O+ + Cl−,\nH3O+ + OH− → 2H2O, NH3 + H3O+ → NH4+ + H2O. Water autoionization is not modeled"},
    {"катализ поверхностью металла (Pt, Pd, Ni, Fe…)", "metal surface catalysis (Pt, Pd, Ni, Fe…)"},
    {"Молекулы, касающиеся атомов Fe, Co, Ni, Cu, Ru, Rh, Pd, Ag, Re, Os, Ir, Pt,\nреагируют с барьером ×0.3 (только кинетическая часть: не ниже ΔH)", "Molecules touching Fe, Co, Ni, Cu, Ru, Rh, Pd, Ag, Re, Os, Ir, Pt atoms\nreact with the barrier ×0.3 (kinetic part only: never below ΔH)"},
    {"зона катализа: вкл", "catalyst zone: on"},
    {"зона катализа", "catalyst zone"},
    {"Зона-катализатор в центре ящика: барьеры ×0.25 внутри круга\n(K — поставить под курсор)", "Catalyst zone at the box center: barriers ×0.25 inside the circle\n(K — place it under the cursor)"},
    {"сбросить журнал", "reset log"},
    {"Очистить журнал реакций и счётчики скоростей", "Clear the reaction log and the rate counters"},
    {"радиус зоны катализа", "catalyst zone radius"},
    {"%.1fσ · %.2f нм", "%.1fσ · %.2f nm"},
    {"Радиус круга (шара), где барьеры реакций уменьшены в 4 раза", "Radius of the circle (sphere) where reaction barriers are 4× lower"},
    {"барьеры реакций ×", "reaction barriers ×"},
    {"Множитель энергий активации (кинетическая часть барьера).\n0 — реакции идут при каждом ударе, но не ниже ΔH", "Activation energy multiplier (kinetic part of the barrier).\n0 — reactions on every collision, but never below ΔH"},
    {"события", "events"},
    {"ассоц. / обмен / дисс.", "assoc. / exch. / diss."},
    {"перенос H+", "H+ transfer"},
    {"включая прыжки по Гроттгусу", "including Grotthuss hops"},
    {"теплота", "heat"},
    {"%+.2f эВ", "%+.2f eV"},
    {"%+.1f ε выделено всего", "%+.1f ε released in total"},
    {"Кислотность (pH)", "Acidity (pH)"},
    {"pH определяется для водных растворов (в сцене нет воды). Сцены «Кислота в воде», «Нейтрализация» — меню сцен.", "pH is defined for aqueous solutions (there is no water in the scene). Scenes “Acid in water”, “Neutralization” — scene menu."},
    {"кислая среда", "acidic"},
    {"щелочная среда", "alkaline"},
    {"нейтральная", "neutral"},
    {"%.3g моль/л", "%.3g mol/L"},
    {"вода", "water"},
    {"%.1f моль/л · V = %.3g л", "%.1f mol/L · V = %.3g L"},
    {"В ящике объёмом ~10⁻²³ л один ион — это ~0.1 моль/л (pH ≈ 1): pH считается по избытку H3O+ или OH−. Вода сама не ионизуется (Kw в такой малой системе — ноль ионов).", "In a box of ~10⁻²³ L a single ion is ~0.1 mol/L (pH ≈ 1): pH is computed from the excess of H3O+ or OH−. Water does not self-ionize (in such a small system Kw means zero ions)."},
    {"Библиотека молекул и структур", "Molecule and structure library"},
    {"свернуть", "collapse"},
    {"вся библиотека (%d)", "full library (%d)"},
    {"Показать все структуры: ионы, кристаллы, кластеры металлов", "Show all structures: ions, crystals, metal clusters"},
    {"Выбрано: %s — %s. ЛКМ в сцене (инструмент «добавить») вставляет со случайной ориентацией.", "Selected: %s — %s. LMB in the scene (the “add” tool) inserts it with a random orientation."},
    {"в центр ящика", "to box center"},
    {"Вставить выбранную структуру в центр ящика", "Insert the selected structure at the box center"},
    {"Нет места в центре — освободите место или вставьте ЛКМ", "No room at the center — make space or insert with LMB"},
    {"5 шт. в случайные места", "5 at random spots"},
    {"Вставить пять копий в случайные свободные места", "Insert five copies at random free spots"},
    {"Вставлено: %d", "Inserted: %d"},
    {"Щёлкните структуру, затем ЛКМ в сцене. Длины связей и углы — реальные (равновесие модели).", "Click a structure, then LMB in the scene. Bond lengths and angles are real (model equilibrium)."},
    {"Состав смеси: %d частиц", "Mixture composition: %d particles"},
    {"… ещё %d веществ", "… %d more substances"},
    {"Журнал реакций", "Reaction log"},
    {"Реакций пока не было (искра — клавиша L, нагрев — ПКМ).", "No reactions yet (spark — key L, heating — RMB)."},
    {"В сцене нет веществ, способных реагировать.", "There are no reactive substances in the scene."},
    {"Выбрать реакцию: её константа скорости и K — ниже", "Select the reaction: its rate constant and K are shown below"},
    {"ΔH %+.0f кДж/моль (%+.2f эВ)", "ΔH %+.0f kJ/mol (%+.2f eV)"},
    {"Кинетика и равновесие", "Kinetics and equilibrium"},
    {"скорость", "speed"},
    {"%.3g соб./τ", "%.3g events/τ"},
    {"за %.1fτ · %.3g соб./пс", "over %.1fτ · %.3g events/ps"},
    {"1/с", "1/s"},
    {"л/(моль·с)", "L/(mol·s)"},
    {"л²/(моль²·с)", "L²/(mol²·s)"},
    {"σ^%d/τ · %.3g %s (порядок %d)", "σ^%d/τ · %.3g %s (order %d)"},
    {"нет реагентов в смеси", "no reactants in the mixture"},
    {"обратная", "reverse"},
    {" — близко к равновесию", " — close to equilibrium"},
    {"не наблюдалась", "not observed"},
    {"по текущим концентрациям", "from current concentrations"},
    {"(моль/л)^%+d, по текущим концентрациям", "(mol/L)^%+d, from current concentrations"},
    {"Ea (Аррениус)", "Ea (Arrhenius)"},
    {"%.2f эВ", "%.2f eV"},
    {"%.0f кДж/моль, все реакции", "%.0f kJ/mol, all reactions"},
    {"Энергия активации по Аррениусу: меняйте T (реакции при разных T) — вкладка «Графики».", "Arrhenius activation energy: vary T (reactions at different T) — the “Plots” tab."},
    {"Атом: заряды и окисление", "Atom: charges and oxidation"},
    {"атом", "atom"},
    {"частичный заряд", "partial charge"},
    {"инкременты связей + EEM иона", "bond increments + ion EEM"},
    {"формальный заряд", "formal charge"},
    {"степень окисления", "oxidation state"},
    {"Полинг / I − A, эВ", "Pauling / I − A, eV"},
    {"молекула", "molecule"},
    {"t=%6.2f T=%.3f P=%.3f dt=%.4f drift=%.4f%% ΣΔE_событий=%.2e a/e/d=%lld/%lld/%lld PT=%lld H3O+=%d OH-=%d pH=%.2f (%.0f шаг/с)\n   mol:", "t=%6.2f T=%.3f P=%.3f dt=%.4f drift=%.4f%% ΣΔE_events=%.2e a/e/d=%lld/%lld/%lld PT=%lld H3O+=%d OH-=%d pH=%.2f (%.0f steps/s)\n   mol:"},
    {"\n   rx ×%lld  %s  ΔH=%+.2f эВ (%+.0f кДж/моль)  r=%.3g/τ", "\n   rx ×%lld  %s  ΔH=%+.2f eV (%+.0f kJ/mol)  r=%.3g/τ"},
    // ---- src/panel_phys.inl
    {"фазовая диаграмма T–ρ (%s, LJ 2.5σ)", "T–ρ phase diagram (%s, LJ 2.5σ)"},
    {"фазовая диаграмма T–ρ (LJ 2.5σ, аргон)", "T–ρ phase diagram (LJ 2.5σ, argon)"},
    {"К", "C"},
    {"тройная %.2f", "triple %.2f"},
    {"г + ж", "g + l"},
    {"флюид", "fluid"},
    {"Агрегатное состояние", "State of matter"},
    {"состояние", "state"},
    {"по диаграмме", "from diagram"},
    {"(для LJ-вещества)", "(for an LJ substance)"},
    {"ΔH плавл.", "ΔH melt."},
    {"%+.2f ε/ат", "%+.2f ε/at"},
    {"%+.2f кДж/моль", "%+.2f kJ/mol"},
    {"ΔH испар.", "ΔH evap."},
    {"Фазовая диаграмма модели (LJ с обрезкой 2.5σ):\nсиняя кривая — бинодаль жидкость–пар, янтарные — плавление/кристаллизация,\nпунктир — тройная линия, К — критическая точка. Красный квадрат — текущее состояние,\nсветлая линия — его путь. Для чистого вещества — в его собственных σ и ε", "Model phase diagram (LJ with a 2.5σ cutoff):\nblue curve — liquid–vapor binodal, amber — melting/crystallization,\ndashed — triple line, C — critical point. Red square — current state,\nlight line — its path. For a pure substance — in its own σ and ε"},
    {"Модель аргона: T*c = %.3f (%.0f K, опыт 150.7 K), тройная T* ≈ %.2f (%.0f K, опыт 83.8 K).", "Argon model: T*c = %.3f (%.0f K, experiment 150.7 K), triple T* ≈ %.2f (%.0f K, experiment 83.8 K)."},
    {"2D-вещество: T*c ≈ 0.459, тройная T* ≈ 0.41 — область жидкости в 2D очень узкая (в 3D: 1.078 и 0.62).", "2D substance: T*c ≈ 0.459, triple T* ≈ 0.41 — the liquid region in 2D is very narrow (in 3D: 1.078 and 0.62)."},
    {"Журнал переходов: %d", "Transition log: %d"},
    {"Переходов пока не было. Нагрейте или охладите вещество (термостат «нагрев P» даёт плато T(t) — теплоту перехода).", "No transitions yet. Heat or cool the substance (the “power heating” thermostat gives a T(t) plateau — the heat of transition)."},
    {"короче", "less"},
    {"подробнее", "more"},
    {"Показать 2 или 8 последних записей", "Show the last 2 or 8 entries"},
    {"очистить журнал", "clear log"},
    {"Очистить журнал фазовых переходов", "Clear the phase transition log"},
    {"Баростат NPT (C-rescale)", "NPT barostat (C-rescale)"},
    {"поддерживать давление (стохастический C-rescale)", "maintain pressure (stochastic C-rescale)"},
    {"Баростат Бернетти–Бусси (2020): объём ящика флуктуирует так,\nчто получается точный NPT-ансамбль при давлении P*.\nРаботает при периодических границах; «поршень» — механический баростат", "Bernetti–Bussi barostat (2020): the box volume fluctuates so that\nthe result is an exact NPT ensemble at pressure P*.\nWorks with periodic boundaries; “piston” is a mechanical barostat"},
    {"Сейчас границы «поршень»: давление задаёт поршень (масса + P внешн.).", "Boundaries are now “piston”: the piston sets the pressure (mass + P ext.)."},
    {"Нужны периодические границы (вкладка «Управление» → Границы).", "Periodic boundaries required (the “Control” tab → Boundaries)."},
    {"P* внешнее", "P* external"},
    {"%.4f · %.1f бар", "%.4f · %.1f bar"},
    {"Целевое давление (ε/σ³; в 2D — на слой толщиной σ).\nПересчёт для аргона: 1 P* = 489 бар", "Target pressure (ε/σ³; in 2D — per layer of thickness σ).\nFor argon: 1 P* = 489 bar"},
    {"τP отклика", "response τP"},
    {"%.2fτ · %.1f пс", "%.2fτ · %.1f ps"},
    {"Время релаксации объёма: меньше — быстрее подстройка,\nбольше — мягче (распределение от τP не зависит)", "Volume relaxation time: smaller — faster adjustment,\nlarger — gentler (the distribution does not depend on τP)"},
    {"P сейчас", "P now"},
    {"%.1f бар · %.2f МПа", "%.1f bar · %.2f MPa"},
    {"объём V", "volume V"},
    {"площадь", "area"},
    {"σ³ · %.1f нм³", "σ³ · %.1f nm³"},
    {"σ² · %.2f нм²", "σ² · %.2f nm²"},
    {"ящик", "box"},
    {"σ · %.2f нм", "σ · %.2f nm"},
    {"В реальных единицах (аргон)", "In real units (argon)"},
    {"%.2f бар", "%.2f bar"},
    {"%.2f атм · %.3f МПа", "%.2f atm · %.3f MPa"},
    {"плотность", "density"},
    {"%.3f г/см³", "%.3f g/cm³"},
    {"%.2f моль/л", "%.2f mol/L"},
    {"E на атом", "E per atom"},
    {"%.3f кДж/моль", "%.3f kJ/mol"},
    {"%.4f эВ (хим.)", "%.4f eV (chem.)"},
    {"время", "time"},
    {"%.2f пс", "%.2f ps"},
    {"шаг %.2f фс", "step %.2f fs"},
    {"ε/k = 139.8 K подобран по критической точке аргона для LJ с обрезкой 2.5σ; σ = 0.3405 нм, τ = 1.0 пс. В 2D давление и плотность — на слой толщиной σ.", "ε/k = 139.8 K is fitted to the argon critical point for LJ with a 2.5σ cutoff; σ = 0.3405 nm, τ = 1.0 ps. In 2D, pressure and density are per layer of thickness σ."},
    {"Объекты поля: %d", "Field objects: %d"},
    {"теплоприток", "heat input"},
    {"отвод %+.2f ε/τ", "removal %+.2f ε/τ"},
    {"испущено", "emitted"},
    {"%lld ат.", "%lld at."},
    {"%.2f ат/τ", "%.2f at/τ"},
    {"поглощено", "absorbed"},
    {"энергия в полях", "field energy"},
    {"(работа при их перемещении — в W)", "(work of moving them goes to W)"},
    {"Устойчивость интегрирования", "Integration stability"},
    {"страж: откат при «взрыве» или NaN", "guard: rollback on “explosion” or NaN"},
    {"Раз в 200 шагов сохраняется снимок. Если появились не-конечные числа\nили T выросла в 50 раз с нарушением баланса энергии —\nоткат к снимку и уменьшение шага dt (затем dt плавно восстанавливается)", "A snapshot is saved every 200 steps. If non-finite numbers appear\nor T grows 50× with a broken energy balance —\nroll back to the snapshot and reduce dt (then dt recovers smoothly)"},
    {"шаг dt", "step dt"},
    {"базовый %.4f%s", "base %.4f%s"},
    {" · огр. ×%.2f", " · limit ×%.2f"},
    {"откатов", "rollbacks"},
    {"огранич. силы: %d", "capped forces: %d"},
    {"(границы не периодические: проверяется только внутренняя часть без стенок)\n", "(boundaries are not periodic: only the interior away from the walls is checked)\n"},
    {"s=%d t=%.1f T=%.4f P=%.4f  газ %.2f жидк %.2f тв %.2f  %s\n", "s=%d t=%.1f T=%.4f P=%.4f  gas %.2f liq %.2f sol %.2f  %s\n"},
    {"s=%d t=%.1f T=%.4f P=%.4f  газ %.2f жидк %.2f тв %.2f  drift=%.2e\n", "s=%d t=%.1f T=%.4f P=%.4f  gas %.2f liq %.2f sol %.2f  drift=%.2e\n"},
    {"RESULT %dD T_triple ≈ %.4f (среднее по второй половине)\n", "RESULT %dD T_triple ≈ %.4f (average over the second half)\n"},
    // ---- src/physics.inl
    {"притягатель", "attractor"},
    {"отталкиватель", "repeller"},
    {"нагреватель", "heater"},
    {"охладитель", "cooler"},
    {"ветер", "wind"},
    {"вихрь", "vortex"},
    {"ловушка", "trap"},
    {"источник", "source"},
    {"сток", "sink"},
    {"барьер", "barrier"},
    {"Притягатель: гладкая потенциальная яма глубиной A (ε) и радиусом R.\nАтомы собираются в каплю вокруг центра; при kT > A — вырываются", "Attractor: a smooth potential well of depth A (ε) and radius R.\nAtoms gather into a droplet around the center; at kT > A they escape"},
    {"Отталкиватель: гладкий потенциальный «холм» высотой A (ε).\nПри A ≫ kT — непроницаемое препятствие (обтекание, ударные волны)", "Repeller: a smooth potential “hill” of height A (ε).\nAt A ≫ kT — an impenetrable obstacle (flow around it, shock waves)"},
    {"Нагреватель: локальный термостат Ланжевена — атомы внутри R\nприходят к температуре зоны Tset (теплота учитывается как внешняя)", "Heater: a local Langevin thermostat — atoms inside R\nreach the zone temperature Tset (the heat counts as external)"},
    {"Охладитель: локальный термостат к низкой Tset —\nна нём конденсируется пар и растут кристаллы", "Cooler: a local thermostat at a low Tset —\nvapor condenses and crystals grow on it"},
    {"Ветер: постоянная сила вдоль направления в области радиуса R\n(работа силы — внешняя). Создаёт поток и перепад давления", "Wind: a constant force along a direction within radius R\n(its work is external). Creates a flow and a pressure difference"},
    {"Вихрь: тангенциальная сила вокруг оси — закручивает газ и жидкость", "Vortex: a tangential force around an axis — swirls gas and liquid"},
    {"Ловушка: узкая гармоническая яма («оптический пинцет»):\nловит отдельные атомы и зародыши", "Trap: a narrow harmonic well (“optical tweezers”):\ncatches single atoms and nuclei"},
    {"Источник: испускает атомы выбранного элемента пучком\n(скорость сопла √((d+2)kT/m)), не создавая перекрытий", "Source: emits a beam of atoms of the chosen element\n(nozzle speed √((d+2)kT/m)) without creating overlaps"},
    {"Сток: удаляет атомы (и небольшие молекулы), попавшие в радиус R.\nВместе с источником — открытая система", "Sink: removes atoms (and small molecules) that enter radius R.\nTogether with a source — an open system"},
    {"Барьер: непроницаемая мягкая стенка (в 2D — отрезок, в 3D — пластина)", "Barrier: an impenetrable soft wall (a segment in 2D, a plate in 3D)"},
    {"ат/τ", "at/τ"},
    {"не-конечные числа", "non-finite numbers"},
    {"температура выросла в 50 раз", "temperature grew 50×"},
    {"Неустойчивость (%s): повреждённые атомы убраны, шаг dt уменьшен до %.4f", "Instability (%s): damaged atoms removed, dt reduced to %.4f"},
    {"Неустойчивость (%s) — откат к t = %.2f, шаг dt уменьшен до %.4f", "Instability (%s) — rollback to t = %.2f, dt reduced to %.4f"},
    // ---- src/presets.inl
    {"1 · Идеальный газ: сравните P с NkT/V (Z = PV/NkT ≈ 1)", "1 · Ideal gas: compare P with NkT/V (Z = PV/NkT ≈ 1)"},
    {"гексагональная", "hexagonal"},
    {"квадратная (неустойчива)", "square (unstable)"},
    {"NaCl (ионная)", "NaCl (ionic)"},
    {"2 · Плавление: ", "2 · Melting: "},
    {" решётка, нагрев P=const → плато T(t). Повтор 2 — другая решётка", " lattice, heating at P=const → T(t) plateau. Repeat 2 — another lattice"},
    {" (для LJ неустойчива → перестраивается в плотную упаковку)", " (unstable for LJ → rearranges into close packing)"},
    {" (для LJ неустойчива → коллапс)", " (unstable for LJ → collapses)"},
    {", нагрев P=const → плато T(t). Повтор 2 — ГЦК/ГПУ/ОЦК/ПК/NaCl/лёд", ", heating at P=const → T(t) plateau. Repeat 2 — FCC/HCP/BCC/SC/NaCl/ice"},
    {"3 · Кипение: жидкость под гравитацией, горячее дно, испарение с поверхности", "3 · Boiling: liquid under gravity, hot bottom, evaporation from the surface"},
    {"4 · Конденсация: пар охлаждается → зародыши → круглые капли (поверхностное натяжение)", "4 · Condensation: vapor cools → nuclei → round droplets (surface tension)"},
    {"5 · Диффузия: перегородка исчезнет через 2τ, смотрите MSD(t) и D", "5 · Diffusion: the partition disappears after 2τ, watch MSD(t) and D"},
    {"6 · NaCl в горячей воде: ионы уходят в раствор, вокруг них гидратные оболочки (ускорьте слайдером «скорость»)", "6 · NaCl in hot water: ions go into solution and get hydration shells (speed it up with the “speed” slider)"},
    {"7 · 2H2 + O2 → 2H2O: искра через 1.5τ (L — ещё вспышка, повтор 7 — H2+Cl2)", "7 · 2H2 + O2 → 2H2O: spark after 1.5τ (L — another flash, repeat 7 — H2+Cl2)"},
    {"7b · H2 + Cl2 → 2HCl: цепная реакция от вспышки света (L)", "7b · H2 + Cl2 → 2HCl: chain reaction from a flash of light (L)"},
    {"8 · Броуновское движение: тяжёлая частица среди атомов, MSD ∝ t", "8 · Brownian motion: a heavy particle among atoms, MSD ∝ t"},
    {"9b · Стекло: бинарная смесь Ar/Ne, резкая закалка (повтор 9 — поликристалл)", "9b · Glass: binary Ar/Ne mixture, rapid quench (repeat 9 — polycrystal)"},
    {"9 · Закалка: поликристалл, границы зёрен, дислокации ([ ] — растянуть до разрушения; повтор 9 — стекло)", "9 · Quench: polycrystal, grain boundaries, dislocations ([ ] — stretch until fracture; repeat 9 — glass)"},
    {"Наночастица золота: металлическая связь (многочастичный потенциал), нагрев → плавление с поверхности", "Gold nanoparticle: metallic bonding (many-body potential), heating → melting from the surface"},
    {"Окисление железа: Fe + O2 → оксид; окисленные атомы теряют металлическую связь (ржавчина отслаивается)", "Iron oxidation: Fe + O2 → oxide; oxidized atoms lose metallic bonding (rust flakes off)"},
    {"Натрий горит в хлоре: 2Na + Cl2 → 2NaCl, ионные пары собираются в кристаллики соли", "Sodium burns in chlorine: 2Na + Cl2 → 2NaCl, ion pairs assemble into small salt crystals"},
    {"Горение метана: CH4 + 2O2 → CO2 + 2H2O (искра через 1.5τ; L — ещё вспышка)", "Methane combustion: CH4 + 2O2 → CO2 + 2H2O (spark after 1.5τ; L — another flash)"},
    {"Электрофорез: поле E гонит Na+ по полю, Cl- — против; вода поляризуется, ток I — в верхней строке", "Electrophoresis: field E drives Na+ along the field, Cl- against it; water polarizes, current I — in the readings"},
    {"Кислота в воде: HCl + H2O → H3O+ + Cl−, протон переходит по цепочке водородных связей (Гроттгус); pH — вкладка «Химия»", "Acid in water: HCl + H2O → H3O+ + Cl−, the proton hops along a chain of hydrogen bonds (Grotthuss); pH — the “Chemistry” tab"},
    {"Нейтрализация HCl + NaOH: H3O+ + OH− → 2H2O; теплота нейтрализации греет раствор, pH → 7. Повтор — титрование", "Neutralization HCl + NaOH: H3O+ + OH− → 2H2O; the heat of neutralization warms the solution, pH → 7. Repeat — titration"},
    {"Титрование: к раствору HCl каждые 1.5τ добавляется порция NaOH; pH скачком проходит 7 в точке эквивалентности", "Titration: a portion of NaOH is added to the HCl solution every 1.5τ; pH jumps through 7 at the equivalence point"},
    {"Горение этанола: C2H5OH + 3O2 → 2CO2 + 3H2O (искра через 1.5τ; L — ещё вспышка)", "Ethanol combustion: C2H5OH + 3O2 → 2CO2 + 3H2O (spark after 1.5τ; L — another flash)"},
    {"Гремучая смесь в закрытом сосуде: 2H2 + O2 → 2H2O; искра через 1τ → взрыв: скачок T и давления (NVE)", "Oxyhydrogen in a closed vessel: 2H2 + O2 → 2H2O; spark after 1τ → explosion: jump in T and pressure (NVE)"},
    {"Катализ на платине: без искры смесь H2 + O2 инертна, но на поверхности наночастицы Pt идёт 2H2 + O2 → 2H2O", "Platinum catalysis: without a spark the H2 + O2 mixture is inert, but 2H2 + O2 → 2H2O proceeds on the surface of the Pt nanoparticle"},
    {"0 · Равновесие Cl2 <=> 2Cl: меняйте T и давление поршня — сдвиг по Ле Шателье", "0 · Equilibrium Cl2 <=> 2Cl: change T and the piston pressure — Le Chatelier shift"},
    {"Дно нагревается → кипение и испарение", "The bottom heats up → boiling and evaporation"},
    {"Охлаждение → пар пересыщен → конденсация", "Cooling → supersaturated vapor → condensation"},
    {"Перегородка убрана", "Partition removed"},
    {"Искра! Энергия вспышки учтена как внешняя работа", "Spark! The flash energy is counted as external work"},
    {"Закалка: T → 0.05–0.1 за доли τ", "Quench: T → 0.05–0.1 within a fraction of τ"},
    {"Включено поле E = 1.5 → катионы дрейфуют по полю, анионы — против", "Field E = 1.5 switched on → cations drift along the field, anions against it"},
    {"Добавлена порция NaOH (Na+ + OH−)", "Added a portion of NaOH (Na+ + OH−)"},
    {"Не удалось добавить NaOH", "Could not add NaOH"},
    {"Идеальный газ", "Ideal gas"},
    {"PV = NkT, распределение Максвелла, давление на стенки", "PV = NkT, Maxwell distribution, pressure on the walls"},
    {"Плавление кристалла", "Crystal melting"},
    {"нагрев постоянной мощностью: плато T(t); повтор 2 — другие решётки", "constant-power heating: T(t) plateau; repeat 2 — other lattices"},
    {"Кипение", "Boiling"},
    {"жидкость под гравитацией, горячее дно, испарение с поверхности", "liquid under gravity, hot bottom, evaporation from the surface"},
    {"Конденсация", "Condensation"},
    {"пересыщенный пар → зародыши → круглые капли", "supersaturated vapor → nuclei → round droplets"},
    {"Диффузия", "Diffusion"},
    {"смешивание двух газов: MSD(t) и коэффициент D", "two gases mixing: MSD(t) and the coefficient D"},
    {"NaCl в воде", "NaCl in water"},
    {"растворение соли, гидратные оболочки ионов", "salt dissolving, hydration shells of ions"},
    {"Горение водорода", "Hydrogen combustion"},
    {"2H2 + O2 → 2H2O от искры; повтор 7 — H2 + Cl2", "2H2 + O2 → 2H2O from a spark; repeat 7 — H2 + Cl2"},
    {"Броуновское движение", "Brownian motion"},
    {"тяжёлая частица среди атомов, MSD ∝ t", "a heavy particle among atoms, MSD ∝ t"},
    {"Закалка", "Quench"},
    {"поликристалл, границы зёрен; повтор 9 — стекло", "polycrystal, grain boundaries; repeat 9 — glass"},
    {"Химическое равновесие", "Chemical equilibrium"},
    {"Cl2 ⇌ 2Cl под поршнем: принцип Ле Шателье", "Cl2 ⇌ 2Cl under a piston: Le Chatelier's principle"},
    {"Наночастица золота", "Gold nanoparticle"},
    {"металлическая связь, плавление начинается с поверхности", "metallic bonding, melting starts at the surface"},
    {"Окисление железа", "Iron oxidation"},
    {"Fe + O2 → оксид: окисленные атомы теряют металлическую связь", "Fe + O2 → oxide: oxidized atoms lose metallic bonding"},
    {"Натрий в хлоре", "Sodium in chlorine"},
    {"2Na + Cl2 → 2NaCl: горение и кристаллики соли", "2Na + Cl2 → 2NaCl: combustion and small salt crystals"},
    {"Горение метана", "Methane combustion"},
    {"CH4 + 2O2 → CO2 + 2H2O: цепная реакция от искры", "CH4 + 2O2 → CO2 + 2H2O: chain reaction from a spark"},
    {"Электрофорез", "Electrophoresis"},
    {"ионы в воде в электрическом поле, ток I", "ions in water in an electric field, current I"},
    {"меню", "menu"},
    {"Кислота в воде", "Acid in water"},
    {"HCl + H2O → H3O+ + Cl−, прыжки протона по Гроттгусу, pH", "HCl + H2O → H3O+ + Cl−, Grotthuss proton hops, pH"},
    {"Нейтрализация", "Neutralization"},
    {"H3O+ + OH− → 2H2O, теплота и pH; повтор — титрование", "H3O+ + OH− → 2H2O, heat and pH; repeat — titration"},
    {"Горение этанола", "Ethanol combustion"},
    {"C2H5OH + 3O2 → 2CO2 + 3H2O от искры", "C2H5OH + 3O2 → 2CO2 + 3H2O from a spark"},
    {"Гремучая смесь", "Oxyhydrogen"},
    {"взрыв 2H2 + O2 в закрытом сосуде: скачок T и P", "2H2 + O2 explosion in a closed vessel: jump in T and P"},
    {"Катализ на платине", "Platinum catalysis"},
    {"H2 + O2 реагируют только на поверхности наночастицы Pt", "H2 + O2 react only on the surface of a Pt nanoparticle"},
    {"Вещество: фазы, перенос, механика", "Matter: phases, transport, mechanics"},
    {"Химия и растворы", "Chemistry and solutions"},
    // ---- src/render.inl
    {"элемент", "element"},
    {"энергия", "energy"},
    {"порядок", "order"},
    {"координация", "coordination"},
    {"фаза", "phase"},
    {" (выкл.)", " (off)"},
    {"  (выкл.)", "  (off)"},
    {"угол  %.1f°", "angle  %.1f°"},
    {"двугр.  %.1f°", "dihedral  %.1f°"},
    {"катализатор", "catalyst"},
    {"%g нм", "%g nm"},
    {"(в центре вида)", "(at view center)"},
    {"цвет — скорость атома", "color — atom speed"},
    {"медленно", "slow"},
    {"быстро", "fast"},
    {"цвет — потенциальная энергия, ε", "color — potential energy, ε"},
    {"цвет — ориентация зерна ψ6, яркость — порядок", "color — grain orientation ψ6, brightness — order"},
    {"цвет — локальная структура", "color — local structure"},
    {"прочее", "other"},
    {"цвет — число соседей", "color — number of neighbors"},
    {"%d норма", "%d normal"},
    {"мало", "few"},
    {"цвет — агрегатное состояние", "color — state of matter"},
    {"газ %.0f%%", "gas %.0f%%"},
    {"жидк. %.0f%%", "liq. %.0f%%"},
    {"тв. %.0f%%", "solid %.0f%%"},
    {"закрепл.", "pinned"},
    {"анализ ещё не готов", "analysis not ready yet"},
    {"цвет — элемент", "color — element"},
    // ---- src/ui.inl
    {"f(v) Максвелл", "f(v) Maxwell"},
    {"пик %.2f при %.2f Å", "peak %.2f at %.2f Å"},
    {"%.1f бар · Z=%.2f", "%.1f bar · Z=%.2f"},
    {"Eполн", "Etot"},
    {"Eп", "Ep"},
    {"Eк", "Ek"},
    {"MSD броун. частицы", "MSD of Brownian particle"},
    {"израсх. %s: %.0f%%", "consumed %s: %.0f%%"},
    {"Молекулы", "Molecules"},
    {"тв.", "solid"},
    {"газ+тв.", "gas+solid"},
    {"ж+г", "l+g"},
    {"Ea ≈ %.2f эВ", "Ea ≈ %.2f eV"},
    {"мало данных", "not enough data"},
    {"T(y) снизу вверх", "T(y) bottom to top"},
    {"Tгор=%.2f Tхол=%.2f", "Thot=%.2f Tcold=%.2f"},
    {"Реакции (самые частые)", "Reactions (most frequent)"},
    {"теплота %+.2f эВ", "heat %+.2f eV"},
    {"реакций пока не было", "no reactions yet"},
    {"в этой сцене нет веществ, способных реагировать", "no reactive substances in this scene"},
    {"ΔH %+.2f эВ", "ΔH %+.2f eV"},
    {"нет", "none"},
    {"лев./прав.", "left/right"},
    {"горячее дно", "hot bottom"},
    {"Сжатие ограничено плотной упаковкой атомов", "Compression is limited by close packing of atoms"},
    {"Поворот невозможен: атомы перекрылись бы с соседями", "Cannot rotate: atoms would overlap with neighbors"},
    {"Откреплено атомов: %d", "Atoms unpinned: %d"},
    {"Закреплено атомов: %d (I — открепить)", "Atoms pinned: %d (I — unpin)"},
    {"Удалено атомов: %d", "Atoms deleted: %d"},
    {"Смена элемента невозможна: новые атомы не помещаются среди соседей", "Cannot change the element: the new atoms do not fit among the neighbors"},
    {"Элемент %s: заменено %d, пропущено %d (не помещаются)", "Element %s: %d replaced, %d skipped (do not fit)"},
    {"Элемент выделенных атомов: %s — %s", "Element of the selected atoms: %s — %s"},
    {"Скопировано атомов: %d, связей: %d (Ctrl+V — вставить у курсора)", "Atoms copied: %d, bonds: %d (Ctrl+V — paste at the cursor)"},
    {"Буфер пуст: выделите атомы и нажмите Ctrl+C", "Clipboard is empty: select atoms and press Ctrl+C"},
    {"Буфер скопирован в другой размерности (2D/3D)", "The clipboard was copied in a different dimension (2D/3D)"},
    {"Вставка не помещается в ящик — сдвиньте курсор", "The paste does not fit in the box — move the cursor"},
    {"Место занято — вставка отменена (сдвиньте курсор)", "Spot is occupied — paste canceled (move the cursor)"},
    {"Вставлено атомов: %d", "Atoms pasted: %d"},
    {"Объект поля удалён", "Field object deleted"},
    {"Объект поля: %s. Колесо — радиус, Shift+колесо — сила, N — вкл/выкл, Del — удалить", "Field object: %s. Wheel — radius, Shift+wheel — strength, N — on/off, Del — delete"},
    {"Добавить / пинцет", "Add / tweezers"},
    {"Ластик", "Eraser"},
    {"Нагрев", "Heat"},
    {"Охлаждение", "Cool"},
    {"Камера", "Camera"},
    {"Выделение", "Selection"},
    {"Толчок", "Push"},
    {"Ударная волна", "Shock wave"},
    {"Ножницы", "Scissors"},
    {"Линейка и угломер", "Ruler & protractor"},
    {"Объекты поля", "Field objects"},
    {"ЛКМ по пустому месту — добавить выбранное вещество (кисть R);\nЛКМ по атому — «пинцет»: атом тянется пружиной за курсором", "LMB on empty space — add the selected substance (brush R);\nLMB on an atom — “tweezers”: a spring pulls the atom after the cursor"},
    {"ЛКМ стирает молекулы под кистью (то же — средняя кнопка мыши)", "LMB erases molecules under the brush (same — middle mouse button)"},
    {"ЛКМ нагревает атомы под кистью (то же — ПКМ).\nПереданная энергия учитывается как внешняя работа W", "LMB heats atoms under the brush (same — RMB).\nThe added energy counts as external work W"},
    {"ЛКМ охлаждает атомы под кистью (то же — Shift+ПКМ)", "LMB cools atoms under the brush (same — Shift+RMB)"},
    {"ЛКМ — вращение камеры (3D) или сдвиг вида (2D), Shift+ЛКМ — сдвиг в 3D.\nВ любом инструменте: Ctrl+ЛКМ — камера, колесо — масштаб", "LMB — rotate the camera (3D) or pan the view (2D), Shift+LMB — pan in 3D.\nIn any tool: Ctrl+LMB — camera, wheel — zoom"},
    {"Рамка — выделить (Shift — добавить), щелчок по атому — вся молекула.\nТащить выделенное — сдвинуть, Alt+тащить — бросок (задать скорость),\nAlt+колесо — поворот. Del — удалить, Ctrl+C/Ctrl+V — копия, I — закрепить", "Box — select (Shift — add), click an atom — its whole molecule.\nDrag the selection — move it, Alt+drag — throw (set a velocity),\nAlt+wheel — rotate. Del — delete, Ctrl+C/Ctrl+V — copy, I — pin"},
    {"ЛКМ — отталкивать атомы от курсора, Shift+ЛКМ — притягивать.\nРадиус — кисть R, сила — «сила инструментов». Работа идёт в W", "LMB — push atoms away from the cursor, Shift+LMB — pull them in.\nRadius — brush R, strength — “tool strength”. The work goes to W"},
    {"Щелчок — ударная волна: радиальный импульс атомам в радиусе 2.5·R.\nСила — «сила инструментов». Энергия удара — внешняя работа W", "Click — shock wave: a radial impulse to atoms within 2.5·R.\nStrength — “tool strength”. The impact energy is external work W"},
    {"Проведите курсором поперёк связей — они рвутся.\nЭнергия разрыва учитывается как внешняя работа W", "Drag the cursor across bonds — they break.\nThe breaking energy counts as external work W"},
    {"Щелчки по атомам: 2 — расстояние, 3 — угол, 4 — двугранный угол (3D).\nЩелчок по пустому месту — сброс. Результаты — во вкладке «Объект»", "Click atoms: 2 — distance, 3 — angle, 4 — dihedral angle (3D).\nClick on empty space — reset. Results are on the “Object” tab"},
    {"ЛКМ — поставить объект выбранного вида (ветер/источник — тянуть по направлению,\nбарьер — от точки к точке); тащить объект — двигать.\nКолесо над объектом — радиус, Shift+колесо — сила; N — вкл/выкл; Del или ПКМ — удалить", "LMB — place an object of the chosen type (wind/source — drag along the direction,\nbarrier — from point to point); drag an object — move it.\nWheel over an object — radius, Shift+wheel — strength; N — on/off; Del or RMB — delete"},
    {"ЛКМ — добавить вещество · по атому — пинцет · двойной щелчок — следить", "LMB — add substance · on an atom — tweezers · double-click — follow"},
    {"ЛКМ — стереть молекулы под кистью", "LMB — erase molecules under the brush"},
    {"ЛКМ — нагревать под кистью (ПКМ — то же)", "LMB — heat under the brush (RMB — same)"},
    {"ЛКМ — охлаждать под кистью (Shift+ПКМ — то же)", "LMB — cool under the brush (Shift+RMB — same)"},
    {"ЛКМ — вращать (3D) / сдвигать (2D) · Shift — сдвиг · колесо — масштаб", "LMB — rotate (3D) / pan (2D) · Shift — pan · wheel — zoom"},
    {"рамка — выделить (Shift +) · тащить — сдвиг · Alt+тащить — бросок · Alt+колесо — поворот · Del · Ctrl+C/V · I — закрепить", "box — select (Shift +) · drag — move · Alt+drag — throw · Alt+wheel — rotate · Del · Ctrl+C/V · I — pin"},
    {"ЛКМ — оттолкнуть · Shift+ЛКМ — притянуть", "LMB — push away · Shift+LMB — pull in"},
    {"щелчок — ударная волна (радиус 2.5·R)", "click — shock wave (radius 2.5·R)"},
    {"тащить поперёк связей — разрезать", "drag across bonds — cut"},
    {"щелчки по атомам: расстояние → угол → двугранный · по пустому — сброс", "click atoms: distance → angle → dihedral · on empty space — reset"},
    {"ЛКМ — поставить/двигать · колесо — R · Shift+колесо — сила · N — вкл/выкл · Del/ПКМ — удалить", "LMB — place/move · wheel — R · Shift+wheel — strength · N — on/off · Del/RMB — delete"},
    {"Инструмент: ", "Tool: "},
    {"АТОМЫ", "ATOMS"},
    {"Сцены", "Scenes"},
    {"Сцены (Tab)\nВсе пресеты с описаниями; повторный выбор — следующий вариант", "Scenes (Tab)\nAll presets with descriptions; picking the same one again — next variant"},
    {"Таблица", "Table"},
    {"Таблица Менделеева (E)\nВсе 118 элементов: выбрать элемент для добавления, источника, смены элемента", "Periodic table (E)\nAll 118 elements: pick an element to add, for a source, or to change the element"},
    {"Продолжить (Пробел)", "Resume (Space)"},
    {"Пауза (Пробел)", "Pause (Space)"},
    {"Один шаг (S)\nСтавит на паузу и делает один шаг интегрирования", "Single step (S)\nPauses and makes one integration step"},
    {"Сброс сцены (R)\nЗаново загрузить текущий пресет (объекты поля сохраняются)", "Reset scene (R)\nReload the current preset (field objects are kept)"},
    {"Отменить (Ctrl+Z)\nВернуть состояние до последнего действия", "Undo (Ctrl+Z)\nRestore the state before the last action"},
    {"Открыть состояние (Ctrl+O)\nF9 — быстрая загрузка", "Open state (Ctrl+O)\nF9 — quick load"},
    {"Сохранить состояние (Ctrl+S)\nF5 — быстрое сохранение", "Save state (Ctrl+S)\nF5 — quick save"},
    {"Снимок сцены в PNG (F12)\nShift+F12 — всё окно; файл — рядом с atoms.exe", "Scene snapshot to PNG (F12)\nShift+F12 — the whole window; the file goes next to atoms.exe"},
    {"Остановить запись кадров (Ctrl+F12)", "Stop frame recording (Ctrl+F12)"},
    {"Запись серии кадров сцены в PNG (Ctrl+F12)\nПапка «кадры_…» рядом с atoms.exe, каждый 2-й кадр", "Record a series of scene frames to PNG (Ctrl+F12)\nFolder “frames_…” next to atoms.exe, every 2nd frame"},
    {"Плоская модель (D — переключить)", "Flat 2D model (D — toggle)"},
    {"Объёмная модель (D — переключить)", "Volumetric 3D model (D — toggle)"},
    {"Боковая панель (G)\nСкрыть/показать панель вкладок — сцена на весь экран", "Side panel (G)\nHide/show the tab panel — the scene fills the window"},
    {"Справка", "Help"},
    {"Клавиши и мышь (H)\nF1 — подробная инструкция в браузере", "Keys and mouse (H)\nF1 — the full manual in the browser"},
    {"t %.2f пс   шаг %lld   %.0f к/с", "t %.2f ps   step %lld   %.0f fps"},
    {"%.1f бар", "%.1f bar"},
    {"г/см³", "g/cm³"},
    {"+%d неподв.", "+%d fixed"},
    {"атомов", "atoms"},
    {"дрейф", "drift"},
    {"% от E", "% of E"},
    {"ε внешн.", "ε ext."},
    {"Eсв", "Ebond"},
    {"τ · %.1f фс", "τ · %.1f fs"},
    {"Доли фаз (подвижные атомы без H)\nгаз %.0f%% · жидкость %.0f%% · твёрдое %.0f%%", "Phase fractions (mobile atoms except H)\ngas %.0f%% · liquid %.0f%% · solid %.0f%%"},
    {"реакций %lld  (ассоц. %lld · обмен %lld · дисс. %lld)", "reactions %lld  (assoc. %lld · exch. %lld · diss. %lld)"},
    {"%sионов в растворе %d/%d", "%sions in solution %d/%d"},
    {"поле E", "field E"},
    {"ток I", "current I"},
    {"огр. F", "F cap"},
    {"случаев", "cases"},
    {"Термостат", "Thermostat"},
    {"Термостат: NVE (энергия сохраняется) → Берендсен → Бусси (канонический)\n→ Ланжевен (трение + шум) → Нозе–Гувер → нагрев постоянной мощностью", "Thermostat: NVE (energy conserved) → Berendsen → Bussi (canonical)\n→ Langevin (friction + noise) → Nosé–Hoover → constant-power heating"},
    {"Термостат: ", "Thermostat: "},
    {"T* цель", "T* target"},
    {"Температура термостата (ε/k). Справа — пересчёт для аргона.\nКолесо мыши над слайдером — точная подстройка", "Thermostat temperature (ε/k). On the right — the value for argon.\nMouse wheel over a slider — fine adjustment"},
    {"τ термостата", "thermostat τ"},
    {"%.2fτ · %.2f пс", "%.2fτ · %.2f ps"},
    {"Время релаксации термостата: меньше — жёстче держит T,\nбольше — ближе к изолированной системе", "Thermostat relaxation time: smaller — holds T more tightly,\nlarger — closer to an isolated system"},
    {"мощность нагрева", "heating power"},
    {"Для режима «нагрев P»: постоянный приток энергии на атом.\nОтрицательная — охлаждение. На фазовом переходе T(t) выходит на плато", "For the “power heating” mode: constant energy input per atom.\nNegative — cooling. At a phase transition T(t) reaches a plateau"},
    {"Давление и границы", "Pressure and boundaries"},
    {"Границы", "Boundaries"},
    {"Границы: периодические → стенки → поршень\n(верхняя стенка под давлением P внешн.)", "Boundaries: periodic → walls → piston\n(the top wall under pressure P ext.)"},
    {"Баростат C-rescale (Бернетти–Бусси): ящик сжимается/расширяется до P внешн.,\nправильные флуктуации объёма (только при периодических границах)", "C-rescale barostat (Bernetti–Bussi): the box shrinks/expands toward P ext.,\ncorrect volume fluctuations (periodic boundaries only)"},
    {"P внешн.", "P ext."},
    {"%.3f · %.0f бар", "%.3f · %.0f bar"},
    {"Внешнее давление: на поршень и для баростата NPT", "External pressure: on the piston and for the NPT barostat"},
    {"Тепловые стенки", "Thermal walls"},
    {"Тепловые стенки: левая горячая / правая холодная (теплопроводность)\nили горячее дно (кипение). Только со стенками", "Thermal walls: hot left / cold right (heat conduction)\nor a hot bottom (boiling). Walls only"},
    {"T горячей стенки", "hot wall T"},
    {"Температура горячей стенки", "Hot wall temperature"},
    {"T холодной стенки", "cold wall T"},
    {"Температура холодной стенки", "Cold wall temperature"},
    {"смачивание стенок", "wall wetting"},
    {"Притяжение атомов к стенкам (потенциал 9-3):\n0 — только отталкивание, 2 — сильное смачивание", "Attraction of atoms to the walls (9-3 potential):\n0 — repulsion only, 2 — strong wetting"},
    {"гравитация g", "gravity g"},
    {"Сила тяжести (только в ящике со стенками)", "Gravity (only in a box with walls)"},
    {"Система", "System"},
    {"размер ящика L", "box size L"},
    {"Размер ящика: атомы масштабируются вместе с ним\n(адиабатическое сжатие/расширение, плавно; работа — в W)", "Box size: atoms are scaled together with it\n(adiabatic compression/expansion, smooth; the work goes to W)"},
    {"число частиц N", "particle count N"},
    {"Число частиц: при отпускании добавляются (выбранное вещество)\nили удаляются случайные молекулы", "Number of particles: on release, molecules are added (the selected substance)\nor random molecules are removed"},
    {"ε притяжение ×", "ε attraction ×"},
    {"Множитель притяжения (LJ и металлической связи):\nбольше — вещество «липче», выше T плавления и кипения", "Attraction multiplier (LJ and metallic bonding):\nlarger — a “stickier” substance, higher melting and boiling T"},
    {"электрическое поле E", "electric field E"},
    {"Поле вдоль x: сила qE на заряженные атомы.\nИоны дрейфуют, вода поворачивается диполями. Работа поля — внешняя", "Field along x: force qE on charged atoms.\nIons drift, water dipoles turn. The field's work is external"},
    {"Химия", "Chemistry"},
    {"химия: вкл", "chemistry: on"},
    {"химия: выкл", "chemistry: off"},
    {"Химические реакции: образование и разрыв связей, обмен атомами", "Chemical reactions: bond formation and breaking, atom exchange"},
    {"Катализатор в центре ящика: барьеры реакций ×0.25 внутри круга\n(K — поставить под курсор)", "Catalyst at the box center: reaction barriers ×0.25 inside the circle\n(K — place it under the cursor)"},
    {"Множитель энергий активации (кинетическая часть барьера).\n0 — реакции идут при любом столкновении, но не ниже ΔH", "Activation energy multiplier (kinetic part of the barrier).\n0 — reactions on any collision, but never below ΔH"},
    {"Интегрирование и инструменты", "Integration and tools"},
    {"скорость, шагов/кадр", "speed, steps/frame"},
    {"Шагов интегрирования за кадр: ускорение времени\n(точность не меняется — шаг dt тот же)", "Integration steps per frame: time acceleration\n(accuracy does not change — dt stays the same)"},
    {"кисть R", "brush R"},
    {"Радиус кисти: добавление, ластик, нагрев, охлаждение, толчок, удар (×2.5), вспышка L", "Brush radius: add, eraser, heat, cool, push, shock (×2.5), flash L"},
    {"сила инструментов", "tool strength"},
    {"Сила толчка, ударной волны и броска выделения", "Strength of push, shock wave and selection throw"},
    {"Отображение", "Display"},
    {"Цвет атомов", "Atom color"},
    {"Режим раскраски (C): элемент → скорость → энергия →\nлокальный порядок → координация → агрегатное состояние", "Coloring mode (C): element → speed → energy →\nlocal order → coordination → state of matter"},
    {"связи", "bonds"},
    {"Химические связи (B); кратные — двойной/тройной линией", "Chemical bonds (B); multiple bonds — double/triple lines"},
    {"следы", "trails"},
    {"Следы траекторий (T)", "Trajectory trails (T)"},
    {"заряды", "charges"},
    {"Частичные заряды: + красным, − голубым кольцом", "Partial charges: + red ring, − blue ring"},
    {"скорости", "velocities"},
    {"Стрелки скоростей атомов", "Atom velocity arrows"},
    {"силы", "forces"},
    {"Стрелки сил (длина ∝ log |F|)", "Force arrows (length ∝ log |F|)"},
    {"объекты поля", "field objects"},
    {"Зоны и значки объектов поля", "Field object zones and icons"},
    {"сетка", "grid"},
    {"Координатная сетка с шагом в нанометрах", "Coordinate grid with a step in nanometers"},
    {"легенда", "legend"},
    {"Легенда цветов в углу сцены", "Color legend in the scene corner"},
    {"линейка масштаба", "scale bar"},
    {"Линейка масштаба (нм/Å) и оси в углу сцены", "Scale bar (nm/Å) and axes in the scene corner"},
    {"закреплённые", "pinned"},
    {"Отметки закреплённых атомов", "Marks on pinned atoms"},
    {"размер шаров", "atom size"},
    {"Только отображение: размер атомов на экране", "Display only: on-screen size of atoms"},
    {"вращение", "rotation"},
    {"Автовращение камеры в 3D (O)", "Camera auto-rotation in 3D (O)"},
    {"Вращение камеры — только в 3D (клавиша D)", "Camera rotation — 3D only (key D)"},
    {"полёт", "fly"},
    {"Полёт камеры в 3D (V): WASD — движение, Q/E — вниз/вверх, Shift — быстрее", "Camera fly mode in 3D (V): WASD — move, Q/E — down/up, Shift — faster"},
    {"Полёт: WASD, Q/E, Shift — быстрее", "Fly mode: WASD, Q/E, Shift — faster"},
    {"Камера: орбита", "Camera: orbit"},
    {"Полёт — только в 3D (клавиша D)", "Fly mode — 3D only (key D)"},
    {"разрез", "section"},
    {"Разрез в 3D (X): показать только то, что за плоскостью;\nShift+колесо — сдвинуть плоскость", "Cross-section in 3D (X): show only what lies behind the plane;\nShift+wheel — move the plane"},
    {"оконный режим", "windowed mode"},
    {"полноэкранный режим", "full screen"},
    {"Полноэкранный режим (F11 или Alt+Enter)", "Full screen (F11 or Alt+Enter)"},
    {"r = (%.2f, %.2f, %.2f) нм", "r = (%.2f, %.2f, %.2f) nm"},
    {"r = (%.2f, %.2f) нм", "r = (%.2f, %.2f) nm"},
    {"v = %.3f σ/τ = %.0f м/с   Eк = %.3f ε", "v = %.3f σ/τ = %.0f m/s   Ek = %.3f ε"},
    {"Eп = %.3f ε   q = %+.2f e   m = %.2f а.е.м.", "Ep = %.3f ε   q = %+.2f e   m = %.2f amu"},
    {"связей: %d  своб. валентн.: %d  %s", "bonds: %d  free valence: %d  %s"},
    {"молекула: %s (%d ат.)", "molecule: %s (%d at.)"},
    {"сетка из %d атомов", "network of %d atoms"},
    {"металлическая связь: %.0f%% (окислен на %.0f%%)", "metallic bonding: %.0f%% (%.0f%% oxidized)"},
    {"коорд. %d   q̄6 = %.2f  q̄4 = %.2f   %s", "coord. %d   q̄6 = %.2f  q̄4 = %.2f   %s"},
    {"коорд. %d   |ψ6| = %.2f", "coord. %d   |ψ6| = %.2f"},
    {"состояние: ", "state: "},
    {"закреплён (I — открепить)", "pinned (I — unpin)"},
    {"Объект поля #%d", "Field object #%d"},
    {"включён", "on"},
    {"выключен", "off"},
    {"Включить/выключить объект (N)", "Turn the object on/off (N)"},
    {"копия", "copy"},
    {"Дублировать объект (со сдвигом)", "Duplicate the object (with an offset)"},
    {"удалить", "delete"},
    {"Удалить объект (Del или ПКМ по значку)", "Delete the object (Del or RMB on its icon)"},
    {"полуширина пластины R", "plate half-width R"},
    {"радиус R", "radius R"},
    {"%.2fσ · %.2f нм", "%.2fσ · %.2f nm"},
    {"Радиус действия (колесо над значком объекта)", "Range radius (wheel over the object icon)"},
    {"сила A", "strength A"},
    {"Сила объекта (Shift+колесо над значком)", "Object strength (Shift+wheel over the icon)"},
    {"вращение: против часовой", "rotation: counterclockwise"},
    {"вращение: по часовой", "rotation: clockwise"},
    {"Сменить направление вращения", "Reverse the direction of rotation"},
    {"T испускания", "emission T"},
    {"T зоны", "zone T"},
    {"Температура зоны / скорость испускаемых атомов", "Zone temperature / speed of emitted atoms"},
    {"направление", "direction"},
    {"Направление (в плоскости): 0° — вправо, 90° — вверх", "Direction (in the plane): 0° — right, 90° — up"},
    {"нормаль: азимут", "normal: azimuth"},
    {"направление: азимут", "direction: azimuth"},
    {"Азимут в плоскости xz", "Azimuth in the xz plane"},
    {"угол возвышения", "elevation angle"},
    {"Угол к плоскости xz (+90° — вверх по y)", "Angle to the xz plane (+90° — up along y)"},
    {"направить по взгляду камеры", "align with camera view"},
    {"Направление/нормаль := направление взгляда", "Direction/normal := view direction"},
    {"элемент: %s  →  взять %s", "element: %s  →  take %s"},
    {"Испускаемый элемент := текущее вещество палитры / таблицы (E)", "Emitted element := current substance of the palette / table (E)"},
    {"концы, нм", "ends, nm"},
    {"центр, нм", "center, nm"},
    {"Выделение: %d ат.", "Selection: %d at."},
    {"состав", "composition"},
    {"T (без ц.м.)", "T (excl. CM)"},
    {"центр масс", "center of mass"},
    {"(%.2f, %.2f, %.2f) нм", "(%.2f, %.2f, %.2f) nm"},
    {"(%.2f, %.2f) нм", "(%.2f, %.2f) nm"},
    {"импульс |p|", "momentum |p|"},
    {"%.3f · v ц.м. %.3f σ/τ", "%.3f · v CM %.3f σ/τ"},
    {"масса", "mass"},
    {"%.1f а.е.м.   закреплено %d", "%.1f amu   pinned %d"},
    {"открепить", "unpin"},
    {"закрепить", "pin"},
    {"Закрепить / открепить (I): интегратор не двигает закреплённые атомы", "Pin / unpin (I): the integrator does not move pinned atoms"},
    {"остановить", "stop"},
    {"Скорости выделенных атомов := 0 (энергия — в W)", "Velocities of the selected atoms := 0 (energy goes to W)"},
    {"нагреть ×1.5 T", "heat ×1.5 T"},
    {"Увеличить тепловые скорости (T ×1.5)", "Increase thermal velocities (T ×1.5)"},
    {"охладить ×0.67 T", "cool ×0.67 T"},
    {"Уменьшить тепловые скорости (T ×0.67)", "Reduce thermal velocities (T ×0.67)"},
    {"элемент → %s", "element → %s"},
    {"Заменить элемент выделенных атомов текущим веществом (связи рвутся)", "Replace the element of the selected atoms with the current substance (bonds break)"},
    {"Удалить выделенные атомы (Del)", "Delete the selected atoms (Del)"},
    {"копировать", "copy"},
    {"Копировать в буфер (Ctrl+C)", "Copy to clipboard (Ctrl+C)"},
    {"вставить", "paste"},
    {"Вставить у курсора (Ctrl+V)", "Paste at the cursor (Ctrl+V)"},
    {"повернуть −15°", "rotate −15°"},
    {"Поворот вокруг центра масс (Alt+колесо)", "Rotate around the center of mass (Alt+wheel)"},
    {"повернуть +15°", "rotate +15°"},
    {"следить", "follow"},
    {"Камера следит за первым атомом выделения", "The camera follows the first selected atom"},
    {"снять выделение", "deselect"},
    {"Снять выделение (Esc)", "Clear the selection (Esc)"},
    {"Камера следит за атомом #%d", "Camera follows atom #%d"},
    {"Измерение", "Measurement"},
    {"атомы", "atoms"},
    {"расстояние 1–2", "distance 1–2"},
    {"угол 1–2–3", "angle 1–2–3"},
    {"двугранный", "dihedral"},
    {"выберите следующий атом…", "pick the next atom…"},
    {"сбросить", "reset"},
    {"Сбросить измерение", "Reset the measurement"},
    {"Атом (слежение)", "Atom (following)"},
    {"Атом", "Atom"},
    {"не следить", "stop following"},
    {"следить камерой", "follow with camera"},
    {"Камера следит за атомом (двойной щелчок по атому)", "The camera follows the atom (double-click an atom)"},
    {"Нет объектов. Инструмент «Объекты поля» (Alt+F, значок внизу слева): выберите вид и щёлкните в сцене.", "No objects. The “Field objects” tool (Alt+F, the icon at the bottom left): pick a type and click in the scene."},
    {"удалить все", "delete all"},
    {"Удалить все объекты поля", "Delete all field objects"},
    {"Выделите атомы (инструмент «Выделение», Alt+2), выберите объект поля, измерьте расстояние (Alt+3) или наведите курсор на атом — подробности появятся здесь.", "Select atoms (the “Selection” tool, Alt+2), pick a field object, measure a distance (Alt+3) or hover over an atom — details will appear here."},
    {"Управление", "Control"},
    {"Физика", "Physics"},
    {"Графики", "Plots"},
    {"Объект", "Object"},
    {"Управление: термостат, давление, система, химия, отображение", "Control: thermostat, pressure, system, chemistry, display"},
    {"Физика: параметры и инструменты физической модели", "Physics: parameters and tools of the physical model"},
    {"Химия: реакции, библиотека молекул", "Chemistry: reactions, molecule library"},
    {"Графики: распределения, временные ряды, кинетика реакций", "Plots: distributions, time series, reaction kinetics"},
    {"Объект: инспектор выделения, объекта поля, измерений и атома", "Object: inspector for the selection, field object, measurements and atom"},
    {"кристалл %.0f%% (ГЦК %d · ГПУ %d · ОЦК %d)   коорд. %.2f   D %.4f", "crystal %.0f%% (FCC %d · HCP %d · BCC %d)   coord. %.2f   D %.4f"},
    {"|ψ6| %.2f   коорд. %.2f   D %.4f σ²/τ", "|ψ6| %.2f   coord. %.2f   D %.4f σ²/τ"},
    {"вид", "type"},
    {"Объект поля: ", "Field object: "},
    {" — щёлкните в сцене", " — click in the scene"},
    {"вещество", "substance"},
    {"%s — %s\nэлемент, выбранный в таблице Менделеева (E)", "%s — %s\nelement picked in the periodic table (E)"},
    {"Стена\nЛКМ (инструмент «добавить») рисует перегородку из неподвижных атомов", "Wall\nLMB (the “add” tool) draws a partition of fixed atoms"},
    {"молекула ", "molecule "},
    {"x %.2f  y %.2f нм", "x %.2f  y %.2f nm"},
    {"%s #%d  (%.2f, %.2f, %.2f) нм", "%s #%d  (%.2f, %.2f, %.2f) nm"},
    {"   слежение #%d", "   following #%d"},
    {"   выделено %d", "   selected %d"},
    {"ПАУЗА", "PAUSED"},
    {"● запись: %d кадр.", "● recording: %d frames"},
    {"стена", "wall"},
    {"%s · %s · %s · ящик %.1f×%.1f%s σ (%.2f×%.2f%s нм)", "%s · %s · %s · box %.1f×%.1f%s σ (%.2f×%.2f%s nm)"},
    {"химия вкл.", "chemistry on"},
    {"химия выкл.", "chemistry off"},
    {" · камера: полёт (WASD, Q/E)", " · camera: fly mode (WASD, Q/E)"},
    {" · разрез %+.1fσ (Shift+колесо)", " · section %+.1fσ (Shift+wheel)"},
    {"#МЫШЬ", "#MOUSE"},
    {"ЛКМ — текущий инструмент (панель слева, Alt+1…Alt+0, Alt+F); наведите на значок — подсказка", "LMB — current tool (panel on the left, Alt+1…Alt+0, Alt+F); hover over an icon — tooltip"},
    {"ПКМ — нагрев, Shift+ПКМ — охлаждение; ПКМ по значку объекта поля — удалить;  СКМ — ластик;  колесо — масштаб", "RMB — heat, Shift+RMB — cool; RMB on a field object icon — delete;  MMB — eraser;  wheel — zoom"},
    {"Ctrl+ЛКМ — камера в любом инструменте;  двойной щелчок по атому — следить камерой;  2D: ЛКМ по поршню — двигать", "Ctrl+LMB — camera in any tool;  double-click an atom — follow it with the camera;  2D: LMB on the piston — move it"},
    {"#ИНСТРУМЕНТЫ", "#TOOLS"},
    {"Alt+1 камера   Alt+2 выделение   Alt+3 линейка/угломер   Alt+4 добавить/пинцет   Alt+5 ластик   Alt+6 нагрев   Alt+7 холод", "Alt+1 camera   Alt+2 selection   Alt+3 ruler/protractor   Alt+4 add/tweezers   Alt+5 eraser   Alt+6 heat   Alt+7 cool"},
    {"Alt+8 толчок (Shift — притяжение)   Alt+9 ударная волна   Alt+0 ножницы (рвать связи)   Alt+F объекты поля", "Alt+8 push (Shift — pull)   Alt+9 shock wave   Alt+0 scissors (break bonds)   Alt+F field objects"},
    {"Выделение: рамка (Shift — добавить), тащить — сдвиг, Alt+тащить — бросок, Alt+колесо — поворот, Ctrl+A — всё", "Selection: box (Shift — add), drag — move, Alt+drag — throw, Alt+wheel — rotate, Ctrl+A — all"},
    {"Del — удалить выделенное / объект поля   Ctrl+C / Ctrl+V — копировать / вставить у курсора   I — закрепить/открепить", "Del — delete the selection / field object   Ctrl+C / Ctrl+V — copy / paste at the cursor   I — pin/unpin"},
    {"Объекты поля: колесо над значком — радиус, Shift+колесо — сила, N — вкл/выкл; параметры — во вкладке «Объект»", "Field objects: wheel over the icon — radius, Shift+wheel — strength, N — on/off; parameters — on the “Object” tab"},
    {"#КАМЕРА 3D", "#3D CAMERA"},
    {"Ctrl+ЛКМ — вращение, Ctrl+Shift+ЛКМ — сдвиг, стрелки — поворот, PgUp/PgDn — ближе/дальше, F/Home — вписать, O — автовращение", "Ctrl+LMB — rotate, Ctrl+Shift+LMB — pan, arrows — turn, PgUp/PgDn — closer/farther, F/Home — fit, O — auto-rotation"},
    {"V — полёт: WASD, Q/E, Shift — быстрее;  F2 спереди, F3 сбоку, F4 сверху, F6 изометрия;  X — разрез, Shift+колесо — плоскость", "V — fly mode: WASD, Q/E, Shift — faster;  F2 front, F3 side, F4 top, F6 isometric;  X — cross-section, Shift+wheel — plane"},
    {"#КЛАВИШИ", "#KEYS"},
    {"D — 2D/3D   Пробел — пауза   S — шаг   R — сброс   G — боковая панель   T — следы   B — связи   C — цвет   H — справка", "D — 2D/3D   Space — pause   S — step   R — reset   G — side panel   T — trails   B — bonds   C — color   H — help"},
    {"U — обратить время   M — сброс MSD   K — катализатор   L — вспышка света   [ ] — сжать/растянуть по x", "U — reverse time   M — reset MSD   K — catalyst   L — flash of light   [ ] — compress/stretch along x"},
    {"F12 — снимок сцены (PNG), Shift+F12 — всё окно, Ctrl+F12 — запись кадров;  F11 / Alt+Enter — полный экран", "F12 — scene snapshot (PNG), Shift+F12 — whole window, Ctrl+F12 — record frames;  F11 / Alt+Enter — full screen"},
    {"F1 — инструкция   F5/F9 — быстрое сохранение/загрузка   Ctrl+S/Ctrl+O — файл   Ctrl+E — CSV   Ctrl+Z — отмена   Esc — закрыть", "F1 — manual   F5/F9 — quick save/load   Ctrl+S/Ctrl+O — file   Ctrl+E — CSV   Ctrl+Z — undo   Esc — close"},
    {"#СЦЕНЫ (Tab — меню; повторное нажатие — вариант)   ·   E — таблица Менделеева", "#SCENES (Tab — menu; press again — variant)   ·   E — periodic table"},
    {"1 идеальный газ   2 плавление   3 кипение   4 конденсация   5 диффузия   6 NaCl в воде   7 горение   8 броуновское движение", "1 ideal gas   2 melting   3 boiling   4 condensation   5 diffusion   6 NaCl in water   7 combustion   8 Brownian motion"},
    {"9 закалка / стекло   0 равновесие Cl2 ↔ 2Cl   Shift+1…5 — золото, окисление железа, Na в хлоре, метан, электрофорез", "9 quench / glass   0 equilibrium Cl2 ↔ 2Cl   Shift+1…5 — gold, iron oxidation, Na in chlorine, methane, electrophoresis"},
    {"в меню (Tab): кислота в воде, нейтрализация (повтор — титрование), горение этанола, гремучая смесь, катализ на платине", "in the menu (Tab): acid in water, neutralization (repeat — titration), ethanol combustion, oxyhydrogen, platinum catalysis"},
    {"Подробная инструкция с объяснением физики — F1 (ИНСТРУКЦИЯ.html).  H или Esc — закрыть", "Full manual with the physics explained — F1 (MANUAL.html).  H or Esc — close"},
    {"в модели: инертен, только ван-дер-ваальс (LJ: σ = %.2f, ε = %.2f)", "in the model: inert, van der Waals only (LJ: σ = %.2f, ε = %.2f)"},
    {"в модели: металлическая связь (многочастичная), E_coh = %.2f эВ; с неметаллами — связи, валентность %d", "in the model: metallic bonding (many-body), E_coh = %.2f eV; bonds with non-metals, valence %d"},
    {"в модели: ковалентные связи, валентность %d", "in the model: covalent bonds, valence %d"},
    {", кратные связи", ", multiple bonds"},
    {"; настроенная модель воды (H-связи, тетраэдричность)", "; tuned water model (H-bonds, tetrahedrality)"},
    {"Выбран %s — %s. ЛКМ в сцене — добавить атомы", "Selected %s — %s. LMB in the scene — add atoms"},
    {"Периодическая система элементов", "Periodic table of the elements"},
    {"щелчок — выбрать · Esc / E — закрыть", "click — select · Esc / E — close"},
    {"%s%s · атомная масса %.3f", "%s%s · atomic mass %.3f"},
    {" · радиоактивен", " · radioactive"},
    {"χ — нет", "χ — none"},
    {" · валентность %d · r_ков = %.2f Å%s", " · valence %d · r_cov = %.2f Å%s"},
    {" · r_мет = %.2f Å", " · r_met = %.2f Å"},
    {"щелчок — открыть (повторный — вариант) · Esc / Tab — закрыть", "click — open (again — variant) · Esc / Tab — close"},
    // ---- строки, которых сейчас нет в исходниках (собираются во время работы или устарели)
    {"Атомы", "Atoms"},
};
